// clientes/livros-angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-livro-lista',
  standalone: true, 
  imports: [CommonModule], 
  templateUrl: './livro-lista/livro-lista.component.html',
  styleUrls: ['./livro-lista/livro-lista.component.css']
})
export class AppComponent {
  title = 'livros-angular';
}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="collapse navbar-collapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="navbar-brand" routerLink="/lista">Catálogo</a>
      </li>
      <li class="nav-item">
        <a class="navbar-brand" routerLink="/dados">Novo</a>
      </li>
    </ul>
  </div>
</nav>

<router-outlet></router-outlet> <!-- Certifique-se de que está fora da barra de navegação -->

// clientes/livros-next/src/App.tsx
import React from 'react';
import { BrowserRouter as Router, Routes, Route, Link } from 'react-router-dom';
import LivroLista from './LivroLista';
import LivroDados from './LivroDados';

const App: React.FC = () => {
  return (
    <Router>
      <nav className="navbar navbar-expand-lg navbar-dark bg-dark">
        <div className="container">
          <Link className="navbar-brand" to="/">Catálogo de Livros</Link>
          <div className="collapse navbar-collapse">
            <ul className="navbar-nav mr-auto">
              <li className="nav-item">
                <Link className="nav-link" to="/">Listagem de Livros</Link>
              </li>
              <li className="nav-item">
                <Link className="nav-link" to="/dados">Cadastro de Livros</Link>
              </li>
            </ul>
          </div>
        </div>
      </nav>

      <div className="container mt-4">
        <Routes>
          <Route path="/" element={<LivroLista />} />
          <Route path="/dados" element={<LivroDados />} />
        </Routes>
      </div>
    </Router>
  );
};

export default App;
