// clientes/livros-angular/src/app/livro-lista/livro-lista.component.ts
import { Component, OnInit } from '@angular/core';
import { ControleLivrosService } from '../controle-livros.service';
import { ControleEditoraService } from '../controle-editora.service';

@Component({
  selector: 'app-livro-lista',
  templateUrl: './livro-lista.component.html',
  styleUrls: ['./livro-lista.component.css'],
})
export class LivroListaComponent implements OnInit {
  livros: any[] = []; // Armazena os livros retornados do backend
  editoras: { codEditora: number; nome: string }[] = [];

  constructor(
    private controleLivros: ControleLivrosService,
    private controleEditoras: ControleEditoraService
  ) {}

  ngOnInit(): void {
    this.carregarLivros();
    this.editoras = this.controleEditoras.getEditoras();
  }

  carregarLivros(): void {
    this.controleLivros.obterLivros().subscribe((dados) => {
      this.livros = dados.map((livroMongo) => ({
        codigo: livroMongo._id,
        ...livroMongo,
      }));
    });
  }

  excluirLivro(codigo: string): void {
    this.controleLivros.excluir(codigo).subscribe(() => {
      this.carregarLivros();
    });
  }

  getNomeEditora(codEditora: number): string {
    const editora = this.editoras.find((e) => e.codEditora === codEditora);
    return editora ? editora.nome : 'Desconhecida';
  }
}

<div class="container mt-4">
  <h1>Catálogo de Livros</h1>
  <table class="table table-striped">
    <thead class="table-dark">
      <tr>
        <th>Título</th>
        <th>Resumo</th>
        <th>Editora</th>
        <th>Autores</th>
        <th>Ações</th>
      </tr>
    </thead>
    <tbody>
      <tr *ngFor="let livro of livros">
        <td>{{ livro.titulo }}</td>
        <td>{{ livro.resumo }}</td>
        <td>{{ getNomeEditora(livro.codEditora) }}</td>
        <td>
          <ul>
            <li *ngFor="let autor of livro.autores">{{ autor }}</li>
          </ul>
        </td>
        <td>
          <button
            class="btn btn-danger btn-sm"
            (click)="excluirLivro(livro.codigo)"
          >
            Excluir
          </button>
        </td>
      </tr>
    </tbody>
  </table>
</div>

// clientes/livros-next/src/LivroLista.tsx
import React, { useState, useEffect } from 'react';
import { ControleLivro } from './controle/ControleLivros';
import { ControleEditora } from './controle/ControleEditora';
import { Livro } from './modelo/Livro';

const controleLivro = new ControleLivro();
const controleEditora = new ControleEditora();

const LinhaLivro = ({ livro, excluir }: { livro: Livro; excluir: (codigo: number) => void }) => {
  const nomeEditora = controleEditora.getNomeEditora(livro.codEditora);

  return (
    <tr>
      <td>
        {livro.titulo}
        <button
          onClick={() => excluir(livro.codigo)}
          className="btn btn-danger btn-sm ms-2"
        >
          Excluir
        </button>
      </td>
      <td>{livro.resumo}</td>
      <td>{nomeEditora}</td>
      <td>
        <ul>
          {livro.autores.map((autor, index) => (
            <li key={index}>{autor}</li>
          ))}
        </ul>
      </td>
    </tr>
  );
};

const LivroLista = () => {
  const [livros, setLivros] = useState<Livro[]>([]);
  const [carregado, setCarregado] = useState(false);

  useEffect(() => {
    if (!carregado) {
      controleLivro
        .obterLivros()
        .then((dados) => setLivros(dados))
        .finally(() => setCarregado(true));
    }
  }, [carregado]);

  const excluir = async (codigo: number) => {
    await controleLivro.excluir(codigo);
    setCarregado(false);
  };

  return (
    <main className="container mt-4">
      <h1>Catálogo de Livros</h1>
      <table className="table table-striped">
        <thead className="table-dark">
          <tr>
            <th>Título</th>
            <th>Resumo</th>
            <th>Editora</th>
            <th>Autores</th>
          </tr>
        </thead>
        <tbody>
          {livros.map((livro) => (
            <LinhaLivro key={livro.codigo} livro={livro} excluir={excluir} />
          ))}
        </tbody>
      </table>
    </main>
  );
};

export default LivroLista;
