// clientes/livros-next/src/LivroDados.tsx
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { ControleLivro } from './controle/ControleLivros';
import { ControleEditora } from './controle/ControleEditora';

const controleLivro = new ControleLivro();
const controleEditora = new ControleEditora();

const LivroDados = () => {
  const [titulo, setTitulo] = useState('');
  const [resumo, setResumo] = useState('');
  const [autores, setAutores] = useState('');
  const [codEditora, setCodEditora] = useState(0);
  const navigate = useNavigate();

  const opcoes = controleEditora.getEditoras().map(editora => ({
    value: editora.codEditora,
    text: editora.nome,
  }));

  const tratarCombo = (evento: { target: { value: any; }; }) => {
    setCodEditora(Number(evento.target.value));
  };

  const incluir = (evento: { preventDefault: () => void; }) => {
    evento.preventDefault();
    const novoLivro = {
      codigo: 0,
      titulo: titulo,
      resumo: resumo,
      autores: autores.split('\n'),
      codEditora: codEditora,
    };
    controleLivro.incluir(novoLivro);
    navigate('/');
  };

  return (
    <main>
      <h1>Cadastro de Livro</h1>
      <form onSubmit={incluir}>
        <div className="form-group">
          <label>Título:</label>
          <input
            type="text"
            className="form-control"
            value={titulo}
            onChange={(e) => setTitulo(e.target.value)}
            required
          />
        </div>

        <div className="form-group">
          <label>Resumo:</label>
          <textarea
            className="form-control"
            value={resumo}
            onChange={(e) => setResumo(e.target.value)}
            required
          />
        </div>

        <div className="form-group">
          <label>Autores (um por linha):</label>
          <textarea
            className="form-control"
            value={autores}
            onChange={(e) => setAutores(e.target.value)}
            required
          />
        </div>

        <div className="form-group">
          <label>Editora:</label>
          <select
            className="form-control"
            value={codEditora}
            onChange={tratarCombo}
          >
            {opcoes.map((opcao) => (
              <option key={opcao.value} value={opcao.value}>
                {opcao.text}
              </option>
            ))}
          </select>
        </div>

        <button type="submit" className="btn btn-primary mt-3">
          Salvar
        </button>
      </form>
    </main>
  );
};

export default LivroDados;

// clientes/livros-angular/src/app/livro-dados/livro-dados.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { CommonModule } from '@angular/common';
import { ControleLivrosService } from '../controle-livros.service';

@Component({
  selector: 'app-livro-dados',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './livro-dados.component.html',
  styleUrls: ['./livro-dados.component.css']
})
export class LivroDadosComponent {
incluirLivro() {
throw new Error('Method not implemented.');
}
  livro = {
    codigo: '',
    titulo: '',
    resumo: '',
    codEditora: 0,
    autores: ['']
  };
titulo: any;
resumo: any;
codEditora: any;
editoras: any;
autores: any;

  constructor(private controleLivros: ControleLivrosService, private router: Router) {}

  incluir() {
    this.controleLivros.incluir(this.livro).subscribe({
      next: () => {
        this.router.navigateByUrl('/lista'); // Redireciona após o sucesso
      },
      error: (err) => {
        console.error('Erro ao incluir o livro:', err); // Trata erros, se necessário
      }
    });
  }
}

<div class="container mt-4">
  <h1>Cadastro de Livro</h1>
  <form>
    <div class="mb-3">
      <label for="titulo" class="form-label">Título</label>
      <input
        type="text"
        id="titulo"
        class="form-control"
        [(ngModel)]="titulo"
        name="titulo"
      />
    </div>
    <div class="mb-3">
      <label for="resumo" class="form-label">Resumo</label>
      <textarea
        id="resumo"
        class="form-control"
        [(ngModel)]="resumo"
        name="resumo"
      ></textarea>
    </div>
    <div class="mb-3">
      <label for="editora" class="form-label">Editora</label>
      <select
        id="editora"
        class="form-select"
        [(ngModel)]="codEditora"
        name="codEditora"
      >
        <option
          *ngFor="let editora of editoras"
          [value]="editora.codEditora"
        >
          {{ editora.nome }}
        </option>
      </select>
    </div>
    <div class="mb-3">
      <label for="autores" class="form-label">Autores (um por linha)</label>
      <textarea
        id="autores"
        class="form-control"
        [(ngModel)]="autores"
        name="autores"
      ></textarea>
    </div>
    <button class="btn btn-primary" (click)="incluirLivro()" type="button">
      Salvar
    </button>
  </form>
</div>
